import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Send, Cpu, FileDown } from 'lucide-react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default function MopiChatPanel({ isOpen, onClose, gridData }) {
  const [messages, setMessages] = useState([
    { id: 1, sender: 'mopi', text: "Hi! I'm Mopi. What kind of custom report would you like me to generate for you today? (e.g. 'Export all Approved deals')" }
  ]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    if (isOpen) {
      scrollToBottom();
    }
  }, [messages, isTyping, isOpen]);

  const generatePDF = (customData, filterText) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.text("Custom CRM Report", 14, 22);
    
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Generated by Mopi AI Filter: "${filterText}"`, 14, 30);
    
    // Table
    const tableColumn = ["Company", "Contact", "Score", "Date", "Value", "Status"];
    const tableRows = [];

    customData.forEach(row => {
      const rowData = [
        row.company,
        row.contact,
        row.score.toString(),
        row.lastContacted,
        `$${row.value.toLocaleString()}`,
        row.legal
      ];
      tableRows.push(rowData);
    });

    doc.autoTable({
      head: [tableColumn],
      body: tableRows,
      startY: 40,
      theme: 'grid',
      headStyles: { fillColor: [22, 163, 74] }, // Green header
    });

    doc.save(`Mopi_Report_${new Date().getTime()}.pdf`);
  };

  const handleSend = () => {
    if (!input.trim()) return;
    
    const userText = input;
    setMessages(prev => [...prev, { id: Date.now(), sender: 'user', text: userText }]);
    setInput('');
    setIsTyping(true);

    // Simulate Mopi thinking
    setTimeout(() => {
      setIsTyping(false);
      
      // Super simple dummy filter
      let filteredData = [...gridData];
      const lowerText = userText.toLowerCase();
      
      if (lowerText.includes('approved')) {
        filteredData = filteredData.filter(d => d.legal.toLowerCase() === 'approved');
      } else if (lowerText.includes('pending')) {
        filteredData = filteredData.filter(d => d.legal.toLowerCase() === 'pending');
      } else if (lowerText.includes('review')) {
        filteredData = filteredData.filter(d => d.legal.toLowerCase() === 'review');
      }
      
      setMessages(prev => [...prev, { 
        id: Date.now(), 
        sender: 'mopi', 
        text: `I've analyzed your request and prepared a report with ${filteredData.length} records. Downloading your PDF now!`,
        action: 'download'
      }]);

      setTimeout(() => {
        generatePDF(filteredData, userText);
      }, 1000);

    }, 1500);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-slate-900/20 backdrop-blur-sm z-40"
          />
          <motion.div
            initial={{ x: '100%' }}
            animate={{ x: 0 }}
            exit={{ x: '100%' }}
            transition={{ type: 'spring', damping: 25, stiffness: 200 }}
            className="fixed top-0 right-0 h-full w-full max-w-md bg-white shadow-2xl z-50 flex flex-col border-l border-slate-200"
          >
            {/* Header */}
            <div className="flex items-center justify-between p-4 border-b border-slate-200 bg-slate-50">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center text-green-600">
                  <Cpu className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-bold text-slate-900">Mopi</h3>
                  <p className="text-xs text-green-600 font-medium flex items-center gap-1">
                    <span className="w-2 h-2 rounded-full bg-green-500"></span> Online
                  </p>
                </div>
              </div>
              <button onClick={onClose} className="p-2 hover:bg-slate-200 rounded-full text-slate-500 transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Chat Area */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-white">
              {messages.map((msg) => (
                <div key={msg.id} className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <div className={`max-w-[80%] rounded-2xl p-3 text-sm shadow-sm ${
                    msg.sender === 'user' 
                      ? 'bg-green-600 text-white rounded-tr-sm' 
                      : 'bg-slate-100 text-slate-800 rounded-tl-sm border border-slate-200'
                  }`}>
                    {msg.text}
                    {msg.action === 'download' && (
                      <div className="mt-2 flex items-center gap-2 text-green-700 bg-white p-2 rounded-lg border border-green-100 shadow-sm">
                        <FileDown className="w-4 h-4" />
                        <span className="font-medium text-xs">Report.pdf Generated</span>
                      </div>
                    )}
                  </div>
                </div>
              ))}
              {isTyping && (
                <div className="flex justify-start">
                  <div className="bg-slate-100 text-slate-500 rounded-2xl rounded-tl-sm p-4 border border-slate-200 flex gap-1 shadow-sm">
                    <motion.div className="w-2 h-2 bg-slate-400 rounded-full" animate={{ y: [0, -5, 0] }} transition={{ repeat: Infinity, duration: 0.6, delay: 0 }} />
                    <motion.div className="w-2 h-2 bg-slate-400 rounded-full" animate={{ y: [0, -5, 0] }} transition={{ repeat: Infinity, duration: 0.6, delay: 0.2 }} />
                    <motion.div className="w-2 h-2 bg-slate-400 rounded-full" animate={{ y: [0, -5, 0] }} transition={{ repeat: Infinity, duration: 0.6, delay: 0.4 }} />
                  </div>
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>

            {/* Input Area */}
            <div className="p-4 border-t border-slate-200 bg-slate-50">
              <div className="relative flex items-center">
                <input
                  type="text"
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                  placeholder="Ask Mopi for a custom report..."
                  className="w-full bg-white border border-slate-300 rounded-full py-3 pl-4 pr-12 text-sm focus:outline-none focus:border-green-500 focus:ring-1 focus:ring-green-500 shadow-sm"
                />
                <button 
                  onClick={handleSend}
                  disabled={!input.trim()}
                  className="absolute right-2 p-2 bg-green-600 text-white rounded-full hover:bg-green-700 disabled:opacity-50 disabled:hover:bg-green-600 transition-colors"
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
